# NumPy Exercises
due to Petr Romov

In [6]:
import numpy as np

SELF. Generate a matrix with 1000 rows and 50 columns, elements being drawn from normal distribution $\mathcal{N}(1, 10)$. Specify random seed to make the result reproducible. Use http://docs.scipy.org/doc/numpy/reference/routines.random.html

In [13]:
mu =1
sigma = 10
matrix= sigma * np.random.randn(1000, 50) + mu

SELF. Normalize the matrix: subtract from each column its mean and divide by the standard deviation. I suggest np.mean, np.std with axis parameter.

In [16]:
def af(x):
    return((x - np.mean(x)) / np.std(x))

np.apply_along_axis(af, 0, matrix)

array([[-0.39135742,  0.87334122,  0.09505005, ...,  1.35144353,
        -0.9575164 , -1.10031056],
       [ 1.73697093,  0.10227028, -0.02660374, ..., -1.49731462,
         0.89954929, -0.62864381],
       [-0.08812675,  0.59585498, -0.96995675, ...,  0.88518057,
         0.22327028, -1.15714531],
       ..., 
       [ 0.87467527, -1.160369  , -0.38177164, ..., -0.26442583,
        -0.51132751, -0.25923778],
       [ 0.55975552,  1.78993275, -0.03195145, ...,  0.75423352,
         1.16890567, -0.01400888],
       [ 1.70232458,  0.22872087, -0.09478057, ..., -0.23232987,
        -0.54121437, -0.16934156]])

Print for the following matrix row numbers for those rows, where element sum is greater than 10. I suggest np.sum and np.nonzero

In [18]:
Z = np.array([[4, 5, 0],
              [1, 9, 3],
              [5, 1, 1],
              [3, 3, 3],
              [9, 9, 9],
              [4, 7, 1]])

In [25]:
np.nonzero(np.sum(Z, 1) > 10)

(array([1, 4, 5]),)

Write a python function to get N largest values from a 1D or 2D array. It should accept as a mandatory parameter N - the number of values to return and optional axis. If axis is not specified, use the flattened array, if specified - return a matrix with N maximum values for each row or column (depends on the axis). BONUS - allow arrays of arbitary dimensions, axis should work as in https://docs.scipy.org/doc/numpy/reference/generated/numpy.amax.html#numpy.amax

In [39]:
def getSort(x, numbers):
    return((-x).argsort()[:numbers])


def doIt(matrix, axis=0, returnvalue= 1):
    if axis == 0:
        np.apply_along_axis(getSort, axis, matrix)
    elif axis == 1:
        pass
    else:
        pass
    
    temp = np.argpartition(matrix, returnvalue, axis)
    return(matrix[temp[:returnvalue]])

doIt(Z)


IndentationError: expected an indented block (<ipython-input-39-bd518a8e2aae>, line 7)

In [46]:
np.sort(Z)


array([[0, 4, 5],
       [1, 3, 9],
       [1, 1, 5],
       [3, 3, 3],
       [9, 9, 9],
       [1, 4, 7]])